import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { PrismaClient } from "@prisma/client";
import styles from "../styles/Home.module.css";

const prisma = new PrismaClient();

interface HomeProps {
  data: any[];
}

export default function Home(props: HomeProps) {
  const { data } = props;

  return (
    <>
      <Head>
        <title>Back office</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ul>
          {data.map((item) => {
            const { id, message, level } = item;
            return (
              <li key={id}>
                <span>{level}</span> - <span>{message}</span>
              </li>
            );
          })}
        </ul>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const logs = await prisma.log.findMany();
  return {
    props: {
      data: logs,
    },
  };
}
